#Importing Libraries

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Loading Dataset
As dataset is a matrix(2-D array), for splicing use syntax [:(to select rows) , :(for columns)] for n-dim use [:,:,......,:]

***iloc*** (Index loaction) is a function in pandas. It will take indexes of rows and columns we want to extract in dataset.

***Feature variables*** in the first n-1 columns.

The ***dependent variable vector*** is in the nth (last column)

We have ***values*** after iloc because we are taking the values.



In [7]:
#loading dataset from github
url = 'https://raw.githubusercontent.com/HarshaR99/Machine_Learning_Course/master/Data_preprocessing/Data.csv?token=AMM77XYADHGGPSB47LHI4Z27AWAJK'
#url needs to be updated during every run
dataset = pd.read_csv(url)
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(x,'\n')
print(y,'\n')
#comparison without using values attr
print(dataset.iloc[:,:-1])

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]] 

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes'] 

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


#Tacking care of missing data
In statistics, ***imputation*** is the process of replacing missing data with substituted values.
[Documentation here](https://scikit-learn.org/0.16/modules/generated/sklearn.preprocessing.Imputer.html#sklearn.preprocessing.Imputer.fit)

In dataframe missing value is represented as ***nan*** of numpy and we are replacing numeric missing data by the mean (can be median,etc) of the column hence *missing_values*=np.nan, *strategy*='mean'.

***fit()*** method fits the imputer on ***x***(feature vairables), connects imputer to matrix of features.

***transform(***) method will do the *replacement* of *missing* data in numeric columns and will return the respective columns.






In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# for fit pass all rows but only numeric columns
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
# notice missing values filled
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


#Encoding Categorical data



##Encoding the independant variable

If we simply assign some number to different categories the model might think their is a numerical order(misinterpreted correlation) among them so we use onehotencoding.

*Sometimes in datasets, we encounter columns that contain numbers of no specific order of preference. The data in the column usually denotes a category or value of the category and also when the data in the column is label encoded.* ~ geeksforgeeks.

---
In ColumnTransformer encoder is the type of tranformatiom
OneHotEncoder is the type of encoding we will do
The list at the end is the index of columns which will undergo this transformation.

Remainder is wheter we keep the remaining columns or not which are not being encoded.

*To train the model it should be in form of numpy array so after transformng convert it to numpy array*.



In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


##Encoding the dependant variable
Just using a label encoder like yes/no = 1/0

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


#Splitting dataset into training and test set

[About random state.](https://)

Test size is 20% of dataset.
Training size is 80%.

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

#Feature scaling
It refers to putting the values in the same range or same scale so that no variable is dominated by the other.

No need to fit again for testing set as standard derivation and mean should be same for both testing and training set.

standardisation = (x - mean(x)) /starndard deviation

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [13]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]
